### KelompokBukuBesar
GET http://localhost:5000/kelompokBukuBesars

###
GET http://localhost:5000/kelompokBukuBesarKodeNama

###
GET http://localhost:5000/kelompokBukuBesars/62dbc51946b14f308bb03a49

###
POST http://localhost:5000/kelompokBukuBesars/
Content-Type: application/json

{
    "kode": "103",
    "nama": "PIUTANG DAGANG",
    "jenis": "AKTIVA"
}

###
PATCH http://localhost:5000/kelompokBukuBesars/62dbc47d46b14f308bb03a3e
Content-Type: application/json

{
    "kode": "101",
    "nama": "KAS",
    "jenis": "AKTIVA"
}

###
DELETE http://localhost:5000/kelompokBukuBesars/62dbc47d46b14f308bb03a3e

### BukuBesar
GET http://localhost:5000/bukuBesars

###
GET http://localhost:5000/bukuBesarKodeNamaKelompok

###
GET http://localhost:5000/bukuBesars/62dbc7e1688587cb053f4665

###
POST http://localhost:5000/bukuBesars/
Content-Type: application/json

{
    "kode": "10102",
    "nama": "KAS KECIL (POS)",
    "kelompok": "101",
    "jenisSaldo": "DEBET",
    "jenis": "KAS/BANK"
}

###
PATCH http://localhost:5000/bukuBesars/62dbc797688587cb053f465b
Content-Type: application/json

{
    "kode": "10101",
    "nama": "KAS BESAR",
    "kelompok": "101",
    "jenis": "DEBET"
}

###
DELETE http://localhost:5000/bukuBesars/62dbc7e1688587cb053f4665

### Jurnal Umums
GET http://localhost:5000/jurnalUmums

###
GET http://localhost:5000/jurnalUmums/62de6cbe1594aed3cdcd6b0a

###
POST http://localhost:5000/jurnalUmums/
Content-Type: application/json

{
    "noJurnalUmum": "1",
    "tanggal": "25-07-2022"
}

###
PATCH http://localhost:5000/jurnalUmums/62de6cbe1594aed3cdcd6b0a
Content-Type: application/json

{
    "totalDebet": 150000,
    "totalKredit": 150000,
    "balance": 0
}

###
DELETE http://localhost:5000/jurnalUmums/62de3cade8487377d8839217

### A Jurnal Umums
GET http://localhost:5000/aJurnalUmums/0002

### 
GET http://localhost:5000/aJurnalUmumForDoc

###
GET http://localhost:5000/aJurnalUmum/62df8c5147909bcb9ed0325e

###
GET http://localhost:5000/aJurnalUmumByNota/1

###
POST http://localhost:5000/aJurnalUmums/
Content-Type: application/json

{
    "noJurnalUmum": "1",
    "kodeAccount": "30101",
    "keterangan": "Pendapatan",
    "debet": 0,
    "kredit": 100000
}

###
PATCH http://localhost:5000/aJurnalUmums/62df393219574ede5325ac3f
Content-Type: application/json

{
    "noJurnalUmum": "1",
    "kodeAccount": "10101",
    "keterangan": "Mendapat kas dari pendapatan",
    "debet": 100000,
    "kredit": 0
}

###
DELETE http://localhost:5000/aJurnalUmums/62e65709d988055e1d3c2d73

### LaporanBukuBesar
GET http://localhost:5000/laporanBukuBesars

###
GET http://localhost:5000/laporanBukuBesarLast/10401

### 
GET http://localhost:5000/laporanBukuBesarByKodeBuku/10401

###
GET http://localhost:5000/laporanBukuBesars/62e23da834f0c6586eebf46b

###
POST http://localhost:5000/laporanBukuBesars/
Content-Type: application/json

{
    "kodeBukuBesar": "30101",
    "tanggal": "27-07-2022",
    "noJurnalUmum": "1",
    "keterangan": "PENDAPATAN PENJUALAN KAS",
    "debet": 0,
    "kredit": 5000000,
    "saldo": 5000000
}

###
DELETE http://localhost:5000/laporanBukuBesars/62e65709d988055e1d3c2d71

### Neraca Saldo
GET http://localhost:5000/neracaSaldos

###
GET http://localhost:5000/neracaSaldos/62e5cae31283839bccf2db7a

### 
GET http://localhost:5000/neracaSaldoForDoc

###
GET http://localhost:5000/neracaSaldoLast/31001

###
POST http://localhost:5000/neracaSaldos/
Content-Type: application/json

{
    "kodeAccount": "30101",
    "jenisAccount": "KREDIT",
    "namaAccount": "PENJUALAN RETAIL",
    "tanggal": "27-07-2022",
    "debet": 0,
    "kredit": 0
}

###
PATCH http://localhost:5000/neracaSaldos/62e5cacd1283839bccf2db67
Content-Type: application/json

{
    "_id": "62e5cacd1283839bccf2db67",
    "tanggal": "26-07-2022",
    "jenisAccount": "DEBET",
    "kodeAccount": "10101",
    "namaAccount": " KAS BESAR",
    "debet": 100000000,
    "kredit": 0
}

###
DELETE http://localhost:5000/neracaSaldos/62e5ce3d1283839bccf2dc54

### Laba Rugi
GET http://localhost:5000/labaRugis

###
GET http://localhost:5000/labaRugis/62e48a1153498c0e99a4e838

###
GET http://localhost:5000/labaRugiTotal

###
GET http://localhost:5000/labaRugiLast

###
GET http://localhost:5000/labaRugiTransaksiAll

###
GET http://localhost:5000/labaRugiTransaksiAllForDoc

###
GET http://localhost:5000/labaRugiTransaksi/30101

###
GET http://localhost:5000/labaRugiTransaksiOther/30101

###
POST http://localhost:5000/labaRugis/
Content-Type: application/json

{
    "tanggal": "28-07-2022",
    "transaksi": [
        {
            "idNeracaSaldo": "62e3c28a50f9184634e5b2ad",
            "kodeAccount": "30101",
            "kelompokAccount": "301",
            "namaAccount": "PENJUALAN RETAIL",
            "total": 5000000
        },
        {
            "idNeracaSaldo": "62e3c2ad50f9184634e5b2c6",
            "kodeAccount": "30401",
            "kelompokAccount": "304",
            "namaAccount": "HPP PENJUALAN RETAIL",
            "total": 3000000
        }
    ],
    "totalPendapatan": 5000000,
    "totalHPP": 3000000,
    "totalBebanOperasional": 0,
    "labaKotor": 2000000,
    "labaBersih": 2000000
}

###
PATCH http://localhost:5000/labaRugis/62e5139999bb09b59d639a4d
Content-Type: application/json

{
    "_id": "62e5139999bb09b59d639a4d",
    "tanggal": "28-07-2022",
    "totalPendapatan": 5000000,
    "totalHPP": 2000000,
    "totalBebanOperasional": 0,
    "labaKotor": 3000000,
    "labaBersih": 3000000,
    "transaksi": [
      {
        "idNeracaSaldo": "62e5d2761283839bccf2dd84",
        "kodeAccount": "30101",
        "namaAccount": " PENJUALAN RETAIL",
        "kelompokAccount": "301",
        "total": 5000000,
        "_id": "62e5d2771283839bccf2dd86"
      },
      {
        "idNeracaSaldo": "62e5d2d41283839bccf2ddb5",
        "kodeAccount": "30401",
        "namaAccount": " HPP PENJUALAN RETAIL",
        "kelompokAccount": "304",
        "total": 2000000,
        "_id": "62e5d2d51283839bccf2ddb8"
      },
      {
        "idNeracaSaldo": "62e5d3661283839bccf2ddf7",
        "kodeAccount": "31001",
        "namaAccount": " BIAYA GAJI",
        "kelompokAccount": "310",
        "total": 0,
        "_id": "62e5dd711283839bccf2de32"
      }
    ]
}

###
DELETE http://localhost:5000/labaRugis/62e5129699bb09b59d639a2b

### Perubahan Modal
GET http://localhost:5000/perubahanModals

### 
GET http://localhost:5000/perubahanModalLast

### 
GET http://localhost:5000/perubahanModalForDoc

###
POST http://localhost:5000/perubahanModals/
Content-Type: application/json

{
    "modalSaham": 0,
    "labaBersih": 0,
    "total": 0
}

###
PATCH http://localhost:5000/perubahanModals/62e626bbd988055e1d3c2b17
Content-Type: application/json

{
    "modalSaham": 0,
    "labaBersih": 0,
    "total": 0
}

###
DELETE http://localhost:5000/perubahanModals/62e62fe2d988055e1d3c2bc2

### Harta
GET http://localhost:5000/hartas

### 
GET http://localhost:5000/hartas/62e66b8d9c78b2c24f0f7414

###
GET http://localhost:5000/hartaLast

###
GET http://localhost:5000/hartaLancarAll

###
GET http://localhost:5000/hartaLancar/10401

###
GET http://localhost:5000/hartaLancarOther/10101

###
GET http://localhost:5000/hartaTetapAll

###
GET http://localhost:5000/hartaTetap/101011

###
GET http://localhost:5000/hartaTetapOther/10101

###
POST http://localhost:5000/hartas/
Content-Type: application/json

{
    "hartaLancar": [
        {
            "kodeAccount": "10101",
            "namaAccount": "KAS BESAR",
            "kelompokAccount": "101",
            "total": 1000000
        },
        {
            "kodeAccount": "10301",
            "namaAccount": "PIUTANG DAGANG",
            "kelompokAccount": "103",
            "total": 1000000
        }
    ],
    "hartaTetap": [
        {
            "kodeAccount": "12001",
            "namaAccount": "TANAH DAN BANGUNAN",
            "kelompokAccount": "120",
            "total": 1000000
        },
        {
            "kodeAccount": "12002",
            "namaAccount": "KENDARAAN",
            "kelompokAccount": "120",
            "total": 1000000
        }
    ],
    "totalHartaLancar": 2000000,
    "totalHartaTetap": 2000000,
    "totalHarta": 4000000
}

###
PATCH http://localhost:5000/hartas/62e66b8d9c78b2c24f0f7414
Content-Type: application/json

{
    "hartaLancar": [
        {
            "kodeAccount": "10101",
            "namaAccount": "KAS BESAR",
            "kelompokAccount": "101",
            "total": 0
        }
    ],
    "hartaTetap": [
        {
            "kodeAccount": "12001",
            "namaAccount": "TANAH DAN BANGUNAN",
            "kelompokAccount": "120",
            "total": 0
        }
    ],
    "totalHartaLancar": 0,
    "totalHartaTetap": 0,
    "totalHarta": 0
}

###
DELETE http://localhost:5000/hartas/62e66b0c9c78b2c24f0f73fb

### Kewajiban
GET http://localhost:5000/kewajibans

###
GET http://localhost:5000/kewajibanLast

###
GET http://localhost:5000/kewajibanAll

###
GET http://localhost:5000/kewajiban/20101

###
GET http://localhost:5000/kewajibanOther/20101

###
POST http://localhost:5000/kewajibans/
Content-Type: application/json

{
    "kewajiban": [
        {
            "kodeAccount": "20101",
            "namaAccount": "HUTANG DAGANG",
            "kelompokAccount": "201",
            "total": 1000000
        }
    ],
    "totalKewajiban": 1000000
}

###
PATCH http://localhost:5000/kewajibans/62e66efa42c5317b501dd049
Content-Type: application/json

{
    "kewajiban": [
        {
            "kodeAccount": "20101",
            "namaAccount": "HUTANG DAGANG",
            "kelompokAccount": "201",
            "total": 0
        }
    ],
    "totalKewajiban": 0
}

###
DELETE http://localhost:5000/kewajibans/62e66ec842c5317b501dd039

### Neraca
GET http://localhost:5000/neracas

### 
GET http://localhost:5000/neracaLast

###
POST http://localhost:5000/neracas/
Content-Type: application/json

{
    "idHarta": "62e66b8d9c78b2c24f0f7414",
    "idKewajiban": "62e66efa42c5317b501dd049",
    "idModal": "62e626bbd988055e1d3c2b17"
}

###
PATCH http://localhost:5000/neracas/62e71bdde259526c8526b991
Content-Type: application/json

{
    "idHarta": "62e66b8d9c78b2c24f0f7414",
    "idKewajiban": "62e66efa42c5317b501dd049",
    "idModal": "62e626bbd988055e1d3c2b17"
}

###
DELETE http://localhost:5000/neracas/62e71bdde259526c8526b991